### ISSUE TITLE
[Bug]: Logo and font blinks on initial-initial load

### ISSUE THREAD

**Issue by andriishupta** [mhmulford0/dd-website-monorepo#14]
### What happened?

When you open the site without cache, somewhy fonts blink, and the logo shows a broken placeholder

https://user-images.githubusercontent.com/10981565/184100181-833c1f74-1126-48ad-b233-032fa4f23257.mov

_Possible_ problem: Next.js doesn't load fonts correctly but takes them to the browser website
It needs investigation, such I am not sure how Next.js works with Initial Paint.

### How to reproduce the bug?

1. Open a new incognito tab
2. Visit the website
3. Observe
4. Reload - with cache, everything is ok

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What device type(s) did you see the problem on?

- [X] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by andriishupta** [comment]
Low priority; could be marked as a `good first issue`, such as it is more of reading docs and doing small tweaks in code

**Comment by mulf0** [comment]
are you seeing this on the new deployment? https://developer-dao-dot-com.vercel.app/

**Comment by andriishupta** [comment]
yes, with emptying cache and hard reload you should also see

<img width="770" alt="image" src="https://user-images.githubusercontent.com/10981565/184175230-0d689c3a-4b24-425e-884a-bb6a6e27bf95.png">
