### ISSUE TITLE
[Feature]: Update Home page buttons to relfect Season 1 Launch

### ISSUE THREAD

**Issue by kempsterrrr** [mhmulford0/dd-website-monorepo#19]
### Context / Background / How This Idea Came To Fruition

Our original website design has two states for the intro section to the landing page; 1 pre $CODE token launch and one post $CODE token launch. The current live design is the pre $CODE token launch design and we need to update this to match the post $CODE token launch design.

### Problem / Opportunity

Improve UX for folks coming to the web website post S1

### Proposed Solution / How It Can Be Improved

n/a

### Testing the changes

Manual

### Additional Information

See designs in [Figma](https://www.figma.com/file/CIsQ5M4bv5CF3R7qNZNAu3/Developer-DAO-website-2022?node-id=0%3A1)

**Comment by kempsterrrr** [comment]
@andriishupta have assigned this one to you for Thursday as discussed on the call. Let me know if you're unable to have any problems with this. thanks!

**Comment by andriishupta** [comment]
@kempsterrrr cool, picking up 👍

**Comment by andriishupta** [comment]
@kempsterrrr ready for review
