### ISSUE TITLE
[Bug]: stale CODE token references

### ISSUE THREAD

**Issue by wolovim** [mhmulford0/dd-website-monorepo#49]
### What happened?

CODE claim window has passed. Scrolling banner needs removing, claim site needs updated context.

### How to reproduce the bug?

Visit homepage and claim site.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What device type(s) did you see the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kempsterrrr** [comment]
i've opened #50 to close this issue
