### ISSUE TITLE
[Feature]: Create "Curated Contributors" as appreciation feature on Home Page

### ISSUE THREAD

**Issue by andriishupta** [mhmulford0/dd-website-monorepo#6]
### Context / Background / How This Idea Came To Fruition

Currently, we have a few images of "history people" on the home page. I suggest creating a separate Collection + Component in Strapi that will fetch random(curated) DAO contributors' accounts: image + Twitter name, for example. 

### Problem / Opportunity

Enhance places where we care about DAO members and let them shine!

### Proposed Solution / How It Can Be Improved

Fetch 5 random people here:
![image](https://user-images.githubusercontent.com/10981565/182876532-f4ada8d4-1ebd-4a4c-a768-fb448caa0be4.png)

### Testing the changes

Tested during implementation

**Comment by andriishupta** [comment]
How it would look like:
![image](https://user-images.githubusercontent.com/10981565/182877463-3a93bd91-624e-42e6-bfad-1f9da21574d5.png)

**Comment by mulf0** [comment]
spoke with the community guild about this, and have solicited some feedback which i think is useful.

> having the founding team volunteer themselves for the v1. and then put out an announcement about it, with a link to sign up or whatever. outreach is easier when people have context for what is being asked.

And

> it would be easy for me to ask members if they’d like to appear on the website during onboarding call. First thing I do is show them the website anyway. 


so we need some legal? work here on the paperwork that grants us a limited use license to the photo of that person. and then some sort of process for requests for takedowns and removals if someone no longer wants to be seen. which I think would be pretty minimal but still needs to exist.
